// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLADEFILEMESSAGE_CIRRUS_MESSAGE_BLADEFILEMESSAGE_H_
#define FLATBUFFERS_GENERATED_BLADEFILEMESSAGE_CIRRUS_MESSAGE_BLADEFILEMESSAGE_H_

#include "flatbuffers/flatbuffers.h"

namespace cirrus {
namespace Message {
namespace BladeFileMessage {

struct Alloc;

struct AllocAck;

struct BladeFileMessage;

enum Data {
  Data_NONE = 0,
  Data_Alloc = 1,
  Data_AllocAck = 2,
  Data_MIN = Data_NONE,
  Data_MAX = Data_AllocAck
};

inline const char **EnumNamesData() {
  static const char *names[] = {
    "NONE",
    "Alloc",
    "AllocAck",
    nullptr
  };
  return names;
}

inline const char *EnumNameData(Data e) {
  const size_t index = static_cast<int>(e);
  return EnumNamesData()[index];
}

template<typename T> struct DataTraits {
  static const Data enum_value = Data_NONE;
};

template<> struct DataTraits<Alloc> {
  static const Data enum_value = Data_Alloc;
};

template<> struct DataTraits<AllocAck> {
  static const Data enum_value = Data_AllocAck;
};

bool VerifyData(flatbuffers::Verifier &verifier, const void *obj, Data type);
bool VerifyDataVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

struct Alloc FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_SIZE = 4,
    VT_FILENAME = 6
  };
  uint64_t size() const {
    return GetField<uint64_t>(VT_SIZE, 0);
  }
  const flatbuffers::String *filename() const {
    return GetPointer<const flatbuffers::String *>(VT_FILENAME);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SIZE) &&
           VerifyOffset(verifier, VT_FILENAME) &&
           verifier.Verify(filename()) &&
           verifier.EndTable();
  }
};

struct AllocBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_size(uint64_t size) {
    fbb_.AddElement<uint64_t>(Alloc::VT_SIZE, size, 0);
  }
  void add_filename(flatbuffers::Offset<flatbuffers::String> filename) {
    fbb_.AddOffset(Alloc::VT_FILENAME, filename);
  }
  AllocBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  AllocBuilder &operator=(const AllocBuilder &);
  flatbuffers::Offset<Alloc> Finish() {
    const auto end = fbb_.EndTable(start_, 2);
    auto o = flatbuffers::Offset<Alloc>(end);
    return o;
  }
};

inline flatbuffers::Offset<Alloc> CreateAlloc(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t size = 0,
    flatbuffers::Offset<flatbuffers::String> filename = 0) {
  AllocBuilder builder_(_fbb);
  builder_.add_size(size);
  builder_.add_filename(filename);
  return builder_.Finish();
}

inline flatbuffers::Offset<Alloc> CreateAllocDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t size = 0,
    const char *filename = nullptr) {
  return cirrus::Message::BladeFileMessage::CreateAlloc(
      _fbb,
      size,
      filename ? _fbb.CreateString(filename) : 0);
}

struct AllocAck FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_REMOTE_ADDR = 4,
    VT_PEER_RKEY = 6
  };
  uint64_t remote_addr() const {
    return GetField<uint64_t>(VT_REMOTE_ADDR, 0);
  }
  uint64_t peer_rkey() const {
    return GetField<uint64_t>(VT_PEER_RKEY, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_REMOTE_ADDR) &&
           VerifyField<uint64_t>(verifier, VT_PEER_RKEY) &&
           verifier.EndTable();
  }
};

struct AllocAckBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_remote_addr(uint64_t remote_addr) {
    fbb_.AddElement<uint64_t>(AllocAck::VT_REMOTE_ADDR, remote_addr, 0);
  }
  void add_peer_rkey(uint64_t peer_rkey) {
    fbb_.AddElement<uint64_t>(AllocAck::VT_PEER_RKEY, peer_rkey, 0);
  }
  AllocAckBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  AllocAckBuilder &operator=(const AllocAckBuilder &);
  flatbuffers::Offset<AllocAck> Finish() {
    const auto end = fbb_.EndTable(start_, 2);
    auto o = flatbuffers::Offset<AllocAck>(end);
    return o;
  }
};

inline flatbuffers::Offset<AllocAck> CreateAllocAck(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t remote_addr = 0,
    uint64_t peer_rkey = 0) {
  AllocAckBuilder builder_(_fbb);
  builder_.add_peer_rkey(peer_rkey);
  builder_.add_remote_addr(remote_addr);
  return builder_.Finish();
}

struct BladeFileMessage FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_DATA_TYPE = 4,
    VT_DATA = 6
  };
  Data data_type() const {
    return static_cast<Data>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const Alloc *data_as_Alloc() const {
    return data_type() == Data_Alloc ? static_cast<const Alloc *>(data()) : nullptr;
  }
  const AllocAck *data_as_AllocAck() const {
    return data_type() == Data_AllocAck ? static_cast<const AllocAck *>(data()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE) &&
           VerifyOffset(verifier, VT_DATA) &&
           VerifyData(verifier, data(), data_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Alloc *BladeFileMessage::data_as<Alloc>() const {
  return data_as_Alloc();
}

template<> inline const AllocAck *BladeFileMessage::data_as<AllocAck>() const {
  return data_as_AllocAck();
}

struct BladeFileMessageBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data_type(Data data_type) {
    fbb_.AddElement<uint8_t>(BladeFileMessage::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(flatbuffers::Offset<void> data) {
    fbb_.AddOffset(BladeFileMessage::VT_DATA, data);
  }
  BladeFileMessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  BladeFileMessageBuilder &operator=(const BladeFileMessageBuilder &);
  flatbuffers::Offset<BladeFileMessage> Finish() {
    const auto end = fbb_.EndTable(start_, 2);
    auto o = flatbuffers::Offset<BladeFileMessage>(end);
    return o;
  }
};

inline flatbuffers::Offset<BladeFileMessage> CreateBladeFileMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    Data data_type = Data_NONE,
    flatbuffers::Offset<void> data = 0) {
  BladeFileMessageBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

inline bool VerifyData(flatbuffers::Verifier &verifier, const void *obj, Data type) {
  switch (type) {
    case Data_NONE: {
      return true;
    }
    case Data_Alloc: {
      auto ptr = reinterpret_cast<const Alloc *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Data_AllocAck: {
      auto ptr = reinterpret_cast<const AllocAck *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return false;
  }
}

inline bool VerifyDataVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyData(
        verifier,  values->Get(i), types->GetEnum<Data>(i))) {
      return false;
    }
  }
  return true;
}

inline const cirrus::Message::BladeFileMessage::BladeFileMessage *GetBladeFileMessage(const void *buf) {
  return flatbuffers::GetRoot<cirrus::Message::BladeFileMessage::BladeFileMessage>(buf);
}

inline bool VerifyBladeFileMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<cirrus::Message::BladeFileMessage::BladeFileMessage>(nullptr);
}

inline void FinishBladeFileMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<cirrus::Message::BladeFileMessage::BladeFileMessage> root) {
  fbb.Finish(root);
}

}  // namespace BladeFileMessage
}  // namespace Message
}  // namespace cirrus

#endif  // FLATBUFFERS_GENERATED_BLADEFILEMESSAGE_CIRRUS_MESSAGE_BLADEFILEMESSAGE_H_
